homeassistant:
  name: !secret home_name
  latitude: !secret home_longitude
  longitude: !secret home_latitude
  elevation: 94
  unit_system: metric
  time_zone: Europe/London
  customize: !include customise.yaml

zone:
  name: !secret home_name
  latitude: !secret home_longitude
  longitude: !secret home_latitude
  radius: 200
  icon: mdi:home

zone 2:
  name: !secret work_name
  latitude: !secret work_longitude
  longitude: !secret work_latitude
  radius: 200
  icon: mdi:glasses

zone 3:
  name: !secret s_work_name
  latitude: !secret s_work_longitude
  longitude: !secret s_work_latitude
  radius: 200
  icon: mdi:school

history:

frontend:

updater:

discovery:

logger:

upnp:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_password


mqtt:
  broker: !secret mqtt_server
  port: !secret mqtt_port
  client_id: home-assistant-1
  keepalive: 60
  username: !secret mqtt_password
  password: !secret mqtt_username

device_tracker:
  - platform: owntracks

# Track the sun
sun:

ifttt:
  key: !secret ifttt_key


# Include List
#device_tracker: !include includes/device_trackers.yaml
input_boolean: !include includes/input_boolean.yaml
input_select: !include includes/input_select.yaml

# Merge List
sensor: !include_dir_merge_list includes/sensors

# Merged Named
group: !include_dir_merge_named includes/group
