homeassistant:
  name: !secret home_name
  latitude: !secret home_longitude
  longitude: !secret home_latitude
  elevation: 94
  unit_system: metric
  time_zone: Europe/London

zone:
  name: !secret home_name
  latitude: !secret home_longitude
  longitude: !secret home_latitude
  radius: 200
  icon: mdi:home

zone 2:
  name: !secret work_name
  latitude: !secret work_longitude
  longitude: !secret work_latitude
  radius: 200
  icon: mdi:glasses

zone 3:
  name: !secret s_work_name
  latitude: !secret s_work_longitude
  longitude: !secret s_work_latitude
  radius: 200
  icon: mdi:school

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_password

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:


# Track the sun
sun:

# Weather Prediction
sensor:
  platform: yweather
  monitored_conditions:
   -  weather
   -  weather_current
   -  temperature
   -  temp_min
   -  temp_max

# Try and find the samsung TV
ifttt:
  key: !secret ifttt_key



#device_tracker: !include includes/device_trackers.yaml

