- platform: fitbit
    monitored_resources:
      "activities/activityCalories"
      "activities/calories"
      "activities/caloriesBMR"
      "activities/distance"
      "activities/elevation"
      "activities/floors"
      "activities/heart"
      "activities/minutesFairlyActive"
      "activities/minutesLightlyActive"
      "activities/minutesSedentary"
      "activities/minutesVeryActive"
      "activities/steps"