############################################################
#
# Glances Sensor
#
############################################################

- platform: glances
  name: Biggs
  host: !secret glances_biggs_host
  port: !secret glances_biggs_port 
  resources:
    - 'disk_use_percent'
    - 'disk_free'
    - 'memory_use_percent'
    - 'processor_load'
    - 'process_running'
    - 'process_total'
    - 'process_thread'
    - 'process_sleeping'

- platform: glances
  name: Wedge
  host: !secret glances_wedge_host
  port: !secret glances_wedge_port 
  resources:
    - 'disk_use_percent'
    - 'disk_free'
    - 'memory_use_percent'
    - 'processor_load'
    - 'process_running'
    - 'process_total'
    - 'process_thread'
    - 'process_sleeping'

- platform: glances
  name: Chocobo
  host: !secret glances_chocobo_host
  port: !secret glances_chocobo_port 
  resources:
    - 'disk_use_percent'
    - 'disk_free'
    - 'memory_use_percent'
    - 'processor_load'
    - 'process_running'
    - 'process_total'
    - 'process_thread'
    - 'process_sleeping'